### ISSUE TITLE
got err reading collection. reissuing query read tcp 54.195.199.181:10065: i/o timeout

### ISSUE THREAD

**Issue by adeshpandey** [compose/transporter#132]
Hi All,
After running 
transporter run --config ./test/config.yaml ./test/application-es.js
I get following error : 
got err reading collection. reissuing query read tcp 54.195.199.181:10065: i/o timeout

application-es.js has following content:
pipeline = Source({
        name: "localmongo",
        namespace: "mongo_schema.collection_name"
    })
    .transform({
        name:"localmongo",
        filename: "transformers/passthrough_and_log.js",
        namespace: "mongo_schema.collection_name"
    })
    .save({
        name: "es",
        namespace: "es_index.doc_type "
    });

is it a bug in the transporter itself or I am doing something wrong?

**Comment by stabenfeldt** [comment]
I get this error occasionally too.
When I restart the transporter it starts immediately and runs for several minutes before it crashes again.

Is there a way to get the transporter to reconnect if it looses it's connection? 
I guess that would be a nice feature for us that run our services in the cloud.

**Comment by sandytrinh** [comment]
Hi there,

I'm also getting this error when I tried to import data from compose.io to my local database. This is my `config.yaml`:

```
nodes:
  infile:
    type: mongo
    uri: mongodb://username:password@host:port/database
    namespace: database./.*/
  outfile:
    type: mongo
    uri: mongodb://localhost/database
    namespace: database./.*/
    bulk: true
```

Transporter seems to import some of the data and then timeout.

Any suggestion on how I can fix this?
