### ISSUE TITLE
Get the progress

### ISSUE THREAD

**Issue by refaelos** [compose/transporter#149]
Is there a way to get the progress of data transfer?

**Comment by ernoaapa** [comment]
:+1:

**Comment by jipperinbham** [comment]
@refaelos yes, in the YAML file specify the following: 

```yaml
api:
  interval: 60s # time interval between metrics posts to the api endpoint
  uri: "WEBHOOK_URl"
```

and transporter will send events to the specified URL every defined interval.
