### ISSUE TITLE
Elasticsearch adaptor requires port in configuration 

### ISSUE THREAD

**Issue by chiefy** [compose/transporter#157]
Was having an issue trying to transport data from Mongo to AWS ES, couldn't figure out why the command wasn't working since I got no errors and the process exited w/ 0. 

didn't import, no errors etc:

``` yaml
...
awselasticsearch:
  type: elasticsearch
  uri: http://my-es.amazon.aws.com
...
```

working:

``` yaml
...
awselasticsearch:
  type: elasticsearch
  uri: http://my-es.amazon.aws.com:80
...
```
