### ISSUE TITLE
Expose certain ENV vars to the JavaScript engine

### ISSUE THREAD

**Issue by chiefy** [compose/transporter#158]
I am trying to use the same `.js` file with different environments (dev/stage/prod). It'd be cool if you could expose environment vars set with a prefix. I was thinking `TRANSPORTER_<VAR_NAME>` but whatever would be great.

**Comment by jipperinbham** [comment]
@chiefy being able to configure an node through environment variables is definitely something that's been discussed

was thinking something along the lines of the following:

```yaml
nodes:
  localmongo:
    type: mongo
    uri: $MONGODB_URI
    namespace: $LOCALMONGO_NS
```
