### ISSUE TITLE
Support for ssl CA File?

### ISSUE THREAD

**Issue by razlupercio** [compose/transporter#202]
I'm having issues connecting to mongodb from transporter:

`you@vps:~/# transporter run --config config.yaml application-es.js clear
js sessions config -> {  }
Mongo Config {URI:mongodb://user:password@host:port/mongodb Namespace:database.collection Ssl:0xc8211ac6a2 Timeout: Debug:true Tail:false Wc:0 FSync:false Bulk:false}
setting start timestamp: 6334667318072705024`

When I log from my laptop I use the sslCAFile option, does transporter support that option? how do I set it?

**Comment by jipperinbham** [comment]
@razlupercio yes, you can provide the CA file in the config.yaml by something like the following:

```yaml
mongoadaptor:
    type: mongo
    uri: mongodb://username:password@hostname:port/database
    ssl:
      cacerts:
      - /path/to/ca_cert.pem
```
