### ISSUE TITLE
mongoDB url with authentication information is not working

### ISSUE THREAD

**Issue by abc123634** [compose/transporter#217]
I'm a newbie to transporter, following all the possible issues and solutions, I finally being able to save local mongo db data to elastic search with config.yaml look like this: ( notice that I use **mongodb** for type because I'm using master branch)

```
nodes:
  localmongo:
    type: mongodb
    uri: mongodb://localhost:27017/foo
    namespace: foo.bar
    tail: false
```

but when I want to add authentication info in order to access my real remote mongo db, it just kept throw the familiar adapter error:
`adaptor 'mongodb' not found in registry`

and the modified config.yaml now looks like this:

```
nodes:
  localmongo:
    type: mongodb
    uri: mongodb://username:password@host:port/dbname
    namespace: dbname.collection
    tail: false
```

At first I though it's because my authentication info was wrong, but even if I add authentication info with localhost (which don't actually have authentication, but it should work, right?), I became unable to access the local db's data.  

```
ubuntu@ip-10-0-7-39:~/go/src/github.com/compose/transporter$ transporter run --config ./test/config.yaml ./test/application.js
Mongo Config {URI:mongodb://username:password@localhost:27017/foo Namespace:foo.bar Ssl:<nil> Timeout: Debug:true Tail:false Wc:0 FSync:false Bulk:false}
adaptor 'mongodb' not found in registry
```

and the authentication-version of config.yaml for localhost look like this:
```
nodes:
  localmongo:
    type: mongodb
    uri: mongodb://username:password@localhost:27017/foo
    namespace: foo.bar
    tail: false
```

So I'm wondering  that the url with authentication is not working, please kindly tell me where did I do wrong and how to fix it, any advice is much appreciated.

**Comment by jipperinbham** [comment]
hi @abc123634, please change the `type` attribute from `mongodb` to `mongo` and see if that helps.

**Comment by abc123634** [comment]
@jipperinbham much thanks for the advice, but it didn't work either even if I changed to `mongo` like this:

```
nodes:
  localmongo:
    type: mongo
    uri: mongodb://localhost:27017/foo
    namespace: foo.bar
    tail: false
```


The error still exist 

`adaptor 'mongo' not found in registry`

and you can notice that it didn't work even if without authentication from above config info.

I think my version of transporter is fine with `mongodb` and local mongodb is working as expected like below.

```
MongoDB shell version: 2.6.12
connecting to: test
> use foo
switched to db foo
> db.bar.find().pretty()
{
	"_id" : ObjectId("585a19ff3052ff841716102c"),
	"firstName" : "Robert",
	"lastName" : "Baratheon"
}
{
	"_id" : ObjectId("585a1a053052ff841716102d"),
	"fi
```rstName" : "John",
	"lastName" : "Snow"
}

Any further suggestion is appreciated.

**Comment by jipperinbham** [comment]
@abc123634 can you try moving the namespace to your application.js file so it'd look as follows:

```javascript
Source({name:"localmongo", debug: true, namespace: "foo.bar"})
.save({name:"foofile", namespace: "foo.bar"})
```

and the YAML would become

```yaml
nodes:
  localmongo:
    type: mongo
    uri: mongodb://localhost:27017/foo
    namespace: foo.bar
    tail: false
```

Also you may have just excluded it from what you pasted previously, I do not see any reference to a `foofile` node defined in the YAML.
