### ISSUE TITLE
facing issue dumping data from mongo to elasticsearch without transformation

### ISSUE THREAD

**Issue by mandeepm91** [compose/transporter#60]
Here are the contents of my tes/config.yaml file and tes/application.js file

`config.yaml`
```
# api:
#   interval: 60s
#   uri: "http://requestb.in/13gerls1"
#   key: "48593282-b38d-4bf5-af58-f7327271e73d"
#   pid: "something-static"
nodes:
  localmongo:
    type: mongo
    uri: mongodb://localhost/foo
  es:
    type: elasticsearch
    uri: http://localhost:9200/
```

`application.js`
```
pipeline = Source({name:"localmongo", namespace:"foo.bar"}).save({name:"es", namespace:"foo.bar"}); 
```

However it fails while inserting to elasticsearch with the error:

```
failed to parse [_id]
```

However, it used to work fine earlier ( a month ago ). Also, if I apply a log transform to see the documents, I can see _id is stored differently:

```
{"_id":{"$oid":"54df376881ee34db87b27377"},"firstName":"Robert","lastName":"Baratheon"}
```

In the transformation, changing 
```
doc._id = doc._id['$oid']; 
```
does solve the problem though. Just want to confirm if there has been a change in the way mongo _id is handled or I am doing something wrong ?
