### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by Garito** [compose/transporter#78]
Hi!
I'm trying to use this library to sync mongodb with elasticsearch but I have a malformed mongo namespace
This is my config.yaml:
```yaml
nodes:
  mongodb:
    type: mongo
    uri: http://mongodb:27017
  es:
    type: elasticsearch
    uri: http://es:9200
```
and this is my application.js
```javascript
pipeline = Source({name:"mongodb", namespace:"tf"}).save({name:"es", namespace:"tf"}); 
```
Obviously I don't understand namespaces (perhaps the lack of documentation has its part on this)
What are namespaces?

How can I configure transporter to replicate a whole database?

Thanks!
